#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

OMLX_VERSION="${OMLX_VERSION:-0.4.4}"
OMLX_DMG_MACOS26="https://github.com/jundot/omlx/releases/download/v${OMLX_VERSION}/oMLX-${OMLX_VERSION}-macos26-27.dmg"
OMLX_DMG_SEQUOIA="https://github.com/jundot/omlx/releases/download/v${OMLX_VERSION}/oMLX-${OMLX_VERSION}-macos15-sequoia.dmg"
APP_PATH="/Applications/oMLX.app"
ENV_FILE="${CONFIG_DIR}/omlx.env"

ensure_dirs

# Use existing API key or default mkapikey (single source of truth)
if [[ -f "$ENV_FILE" ]] && grep -q '^OMLX_API_KEY=' "$ENV_FILE"; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  log "Reusing existing oMLX API key"
else
  OMLX_API_KEY="${OMLX_API_KEY:-mkapikey}"
  cat > "$ENV_FILE" <<EOF
# Generated by local-inference bootstrap — do not commit
OMLX_HOST=127.0.0.1
OMLX_PORT=8000
OMLX_MODEL_DIR=${HOME}/models
OMLX_API_KEY=${OMLX_API_KEY}
OMLX_BASE_URL=http://127.0.0.1:8000/v1
OMLX_ADMIN_URL=http://127.0.0.1:8000/admin
EOF
  chmod 600 "$ENV_FILE"
  log "Wrote oMLX API key (mkapikey) at ${ENV_FILE}"
fi

mkdir -p "${HOME}/models"

if [[ -d "$APP_PATH" ]]; then
  log "oMLX already installed at ${APP_PATH}"
else
  log "Downloading oMLX v${OMLX_VERSION}..."
  tmp_dmg="$(mktemp -t omlx.XXXXXX.dmg)"
  macos_major="$(macos_major_version)"
  if [[ "$macos_major" -ge 26 ]]; then
    dmg_url="$OMLX_DMG_MACOS26"
  else
    dmg_url="$OMLX_DMG_SEQUOIA"
  fi

  curl -fL --progress-bar -o "$tmp_dmg" "$dmg_url"
  mount_output="$(hdiutil attach "$tmp_dmg" -nobrowse 2>&1)"
  mount_point="$(echo "$mount_output" | grep -o '/Volumes/[^[:space:]]*' | tail -1)"
  if [[ -z "$mount_point" ]]; then
    mount_point="$(echo "$mount_output" | awk -F'\t' '/\/Volumes\// {print $NF; exit}')"
  fi
  [[ -n "$mount_point" && -d "$mount_point" ]] || die "Failed to mount oMLX DMG: $mount_output"

  if [[ -d "${mount_point}/oMLX.app" ]]; then
    cp -R "${mount_point}/oMLX.app" /Applications/
  else
    cp -R "${mount_point}/"*.app /Applications/ 2>/dev/null || die "oMLX.app not found in DMG at $mount_point"
  fi
  hdiutil detach "$mount_point" -quiet || hdiutil detach "$(dirname "$mount_point")" -quiet || true
  rm -f "$tmp_dmg"
  log "Installed oMLX to ${APP_PATH}"
fi

# Login item via launchd (opens menu bar app)
install_launchd_plist "com.omlx.serve"
open -a oMLX 2>/dev/null || true

log "Waiting for oMLX API..."
load_omlx_env
auth_header="Authorization: Bearer ${OMLX_API_KEY}"
for _ in $(seq 1 45); do
  if curl -sf -H "$auth_header" "http://127.0.0.1:8000/v1/models" >/dev/null 2>&1; then
    log "oMLX is running on http://127.0.0.1:8000"
    log "Admin UI: http://127.0.0.1:8000/admin"
    exit 0
  fi
  # Also accept unauthenticated health during first-run setup
  if curl -sf "http://127.0.0.1:8000/health" >/dev/null 2>&1; then
    log "oMLX health endpoint up — configure API key in app if requests fail"
    exit 0
  fi
  sleep 2
done

warn "oMLX app installed but API not yet reachable."
warn "Open oMLX from Applications, set model dir to ~/models, enable API key, and start the server."
warn "API key is in ${ENV_FILE} — paste it into oMLX settings if prompted."
